### ISSUE TITLE
Excessive console.logs cluttering console output

### ISSUE THREAD

**Issue by droidenator** [abdennour/xclass#1]
I've started using `xclass` because I'm using your library for `js-curl`. So far, `js-curl` has been able to help me get an XML file that no other library was able to receive so thank you for that!

However, I've noticed that your modules tend to be a bit verbose and will probably fill up my logs with a lot of debug statements. Would you be opposed to a PR to disable the `console.log` statements if the `NODE_ENV` is not set to `develop`? Also, I could not find a repo for `js-curl` but I'd be glad to submit a similar PR for it.

**Comment by abdennour** [comment]
Thank you for your review & feedback . I will work on this issue as soon as possible.
